# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89006fa20a64c85961b5abdec5339a6ae1bb469e68b635ecbe105072a61c24157032fc34cf4335843a841311e35e0a5bfbb6410b8b5803b10ed91a838b148995

test:
  secret_key_base: b4449e90a2c8798837ad0d71845998c11122883a4d155542497abf95b804615bbc0ad81030ce5d7f0871b3393b148801c24b6212f086c4108e79fe29eda0ec47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
